Hardware and configuration selections and travis build server setup
DzikuVx/QuadMeUp_Crossbow pull request #47
Opened 2018-02-10 22:48 UTC by unitware

(This PR is admittely a bit chunky, please let me know if you want me to split it more commits)

I have added support to build all combinations of the application on travis (see https://travis-ci.org/unitware/QuadMeUp_Crossbow).

The matrix is set up with two hardwares (feather 32u4, feather M0) and some different sets of defines testing both rx and tx, and variants of tx to use ppm input or sbus input.

All combinations are specified in configurations/config_nn_nn.h and one of these files are moved to replace the config.h file when building. (I did it this way since I did not find a way to inject the configurations when scripting the build.)

There are also some changes to the tx input implementation to unify the interface between ppm and sbus input. I hope I got the licensing right in that case (combining MPL and GPL3)

2018-02-11 12:16 UTC, DzikuVx commented
@unitware could you split this into 2 separate PRs please? 
Besides that, cool, thanks!

2018-02-11 12:20 UTC, DzikuVx requested changes
Split Travis into seprate PR please and remove ppm decoding since it's not used and should not be used

2018-02-11 12:20 UTC, DzikuVx commented on crossbow/ppm_reader.cpp
> +/*
Latest version is not using PPM decoding and probably will never be. OpenTX 2.2.1 already has been published and there is no need to fallback to such old protocol as PPM

2018-02-11 12:36 UTC, unitware commented
I can split the PR and leave out the ppm, no problem. But I’d like yo keep the infrastructure to be able to select tx input. I do not have any hardware that outputs sbus so I need to keep those files for my own use. 

The GPL3 will disappear when removing the ppm_reader and that makes it easier :)

Skickat från min iPhone

> 11 feb. 2018 kl. 13:20 skrev Paweł Spychalski <notifications@github.com>:
> 
> @DzikuVx requested changes on this pull request.
> 
> Split Travis into seprate PR please and remove ppm decoding since it's not used and should not be used
> 
> In crossbow/ppm_reader.cpp:
> 
> > @@ -0,0 +1,102 @@
> +/*
> Latest version is not using PPM decoding and probably will never be. OpenTX 2.2.1 already has been published and there is no need to fallback to such old protocol as PPM
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2018-02-11 12:55 UTC, DzikuVx commented
Yea... I keep forgetting that PPMReader is GPL not MPL. Even my own code ;)

2018-02-11 18:50 UTC, unitware commented
so, I removed the GPL3 stuff - that is the ppm_reader and the licensing text.

I left the TxInput base class to make it easier for me to keep in track with your master later on. I am using it for ppm and maybe later also a variant with analog inputs so I can build a new tx from an old one with just the feather board inside. 

Does this feel ok?

2018-02-12 08:44 UTC, DzikuVx commented
I will gry to test in a next few days on a real hardware of mine

2018-02-12 14:48 UTC, DzikuVx commented
OK, let's see how it goes... compiles on Lora32u4 had no time to test it further tho

2018-02-12 14:48 UTC, merged

2018-02-12 14:57 UTC, unitware commented
great, now log in to travis and enable the repo :)
https://travis-ci.org/DzikuVx